---
- name: install nfs pakcages
  apt: name=nfs-kernel-server,nfs-common,rpcbind state=latest

- name: stop nfs
  service: name=nfs-kernel-server state=stopped

- name: stop rpcbind
  service: name=rpcbind state=stopped

#- name: unmount existing volumes
#  shell: umount {{mount_volume_path}} || true
#
#- name: create a ext4 filesystem on /dev/sdb
#  filesystem: fstype=ext4 dev=/dev/sdb
#
- name: create mount directory
  file: name={{mount_volume_target}} state=directory
#
#- name: mount storage volume
#  mount: name={{mount_volume_path}} src=/dev/sdb fstype=ext4 state=mounted

#- name: bind mount to export directory
#  mount: name=/export src={{mount_volume_path}} fstype=none opts=bind state=mounted

- name: install /etc/exports
  template: src=exports dest=/etc/exports mode=0644

- name: start rpcbind
  service: name=rpcbind state=started

- name: start nfs-server
  service: name=nfs-kernel-server state=started

- name: create home directories
  file: path={{mount_volume_target}}/home state=directory

- name: create home directories
  file: path={{mount_volume_target}}/home/{{ item }} state=directory group=1000 owner=1000 recurse=yes
  with_items:
  - "{{ jupyterhub_admins }}"
  - "{{ jupyterhub_users }}"
  tags:
  - add_users
