---
- name: disable selinux
  selinux: state=disabled
  register: selinux
  tags:
  - hadoop

- name: reboot host
  shell: nohup bash -c "sleep 2s && reboot" &
  register: reboot
  when: selinux.changed

- name: wait for host boot
  local_action:
    module: wait_for
    host: "{{ ansible_ssh_host }}"
    port: 22
    delay: "{{ boot_wait | default(60) }}"
    timeout: 120
    state: started
  when: selinux.changed

- name: create the hadoop directory
  file: path=/srv/hadoop state=directory
  tags:
  - hadoop

- name: copy the Dockerfile to the hadoop directory
  template: src=Dockerfile.hadoop.j2 dest=/srv/hadoop/Dockerfile
  tags:
  - hadoop

- name: copy bootstrap.sh to the hadoop directory
  copy: src=bootstrap.sh dest=/srv/hadoop/singleuser.sh
  tags:
  - hadoop

- name: pull lcdm/info490-hadoop image
  shell: docker pull lcdm/info490-hadoop:latest
  tags:
  - hadoop

- name: build hadoop image
  shell: docker build -t hadoop /srv/hadoop
  tags:
  - hadoop
