---
- hosts:
  - proxy
  - jupyterhub_host
  - jupyterhub_nodes
  - nfs_server
  - consul_server
  roles:
  - common
  tags:
  - common

- hosts:
  - proxy
  - jupyterhub_host
  - jupyterhub_nodes
  - nfs_server
  - consul_server
  vars_files:
  - vars.yml
  roles:
  - docker
  tags:
  - docker

- hosts:
  - nfs_server
  vars_files:
  - users.yml
  - vars.yml
  roles:
  - nfs_server
  - cron
  - duplicity
  tags:
  - nfs
  - nfs_server

- hosts:
  - nfs_clients
  vars_files:
  - vars.yml
  roles:
  - nfs_client
  tags:
  - nfs
  - nfs_client

- hosts:
  - jupyterhub_host
  vars_files:
  - vars.yml
  roles:
  - consul_server
  tags:
  - consul
  - consul_server

- hosts:
  - jupyterhub_nodes
  vars_files:
  - vars.yml
  roles:
  - consul_client
  tags:
  - consul
  - consul_client

- hosts:
  - jupyterhub_nodes
  vars_files:
  - vars.yml
  roles:
  - singleuser

- hosts: 
  - jupyterhub_host
  vars_files:
  - users.yml
  - vars.yml
  roles:
  - hub
  tags:
  - hub

- hosts:
  - proxy
  vars_files:
  - vars.yml
  roles:
  - proxy
  tags:
  - proxy

