FROM lcdm/info490-hadoop:latest

USER root

# fetch juptyerhub-singleuser entrypoint
ADD https://raw.githubusercontent.com/minrk/jupyterhub/a35f6298f0ed850f9cf4884c459a9ff13a40df7e/scripts/jupyterhub-singleuser /usr/local/bin/jupyterhub-singleuser
RUN chmod 755 /usr/local/bin/jupyterhub-singleuser

ADD singleuser.sh /srv/singleuser/singleuser.sh
RUN chown $NB_USER:hadoop /srv/singleuser/singleuser.sh && \
    chmod 700 /srv/singleuser/singleuser.sh

CMD ["/srv/singleuser/singleuser.sh"]

USER data_scientist

ENV PYTHONPATH /home/data_scientist/.info490/rubric
