FROM centos:centos7

MAINTAINER Edward J Kim <edward.junhyung.kim@gmail.com>

RUN yum -y update && \
    yum -y install vim wget && \
    wget -P /etc/yum.repos.d \
        http://download.opensuse.org/repositories/security://shibboleth/CentOS_7/security:shibboleth.repo && \
    yum -y install httpd shibboleth.x86_64 && \
    chmod +x /etc/shibboleth/shibd-redhat && \
    yum -y install mod_ssl

RUN cd /etc/httpd/conf && \
    echo 'UseCanonicalName On' >> httpd.conf && \
    echo 'LoadModule proxy_module modules/mod_proxy.so' >> httpd.conf && \
    echo 'LoadModule proxy_http_module modules/mod_proxy_http.so' >> httpd.conf && \
    echo 'LoadModule ssl_module modules/mod_ssl.so' >> httpd.conf && \
    echo 'LoadModule proxy_wstunnel_module mod_proxy_wstunnel.so' >> httpd.conf && \
    echo 'Include /etc/httpd/conf/extra/httpd-vhosts.conf' >> httpd.conf && \
    mkdir /var/run/lock  && \
    mkdir /var/lock/subsys

COPY httpd-vhosts.conf /etc/httpd/conf/extra/httpd-vhosts.conf
COPY shib.conf /etc/httpd/conf.d/shib.conf
COPY httpd-foreground /usr/local/bin/
COPY certs/ca.key /etc/httpd/certs/ca.key
COPY certs/ca.crt /etc/httpd/certs/ca.crt
COPY shibboleth2.xml /etc/shibboleth/shibboleth2.xml
COPY attribute-map.xml /etc/shibboleth/attribute-map.xml

EXPOSE 80 443

CMD ["/usr/local/bin/httpd-foreground"]
