---
- name: create the cron directory
  file: path=/srv/cron state=directory
  tags:
  - cron

- name: copy crontab
  template: src=crontab.j2 dest=/srv/cron/crontab
  tags:
  - cron

- name: create the studentlist
  template: src=studentlist.j2 dest=/srv/cron/studentlist
  tags:
  - cron

- name: copy Dockerfile for cron
  copy: src=Dockerfile dest=/srv/cron/Dockerfile
  tags:
  - cron

- name: copy release_to_students.sh
  copy: src=release_to_students.sh dest=/srv/cron/release_to_students.sh
  tags:
  - cron

- name: copy collect.sh
  copy: src=collect.sh dest=/srv/cron/collect.sh
  tags:
  - cron

- name: stop and remove cron container
  shell: docker ps | grep root_cron_1 > /dev/null && docker rm -f root_cron_1 || true
  tags:
  - cron

- name: bulid cron image
  command: docker build -t cron /srv/cron
  tags:
  - cron

- name: run cron container
  command: docker run -d --name root_cron_1 -v /export:/export cron
  tags:
  - cron
