FROM jupyterhub/jupyterhub:0.7.1

MAINTAINER Edward J Kim <edward.junhyung.kim@gmail.com>

RUN apt-get update && \
    pip install --upgrade pip && \
    pip install docker-py && \
    pip install git+git://github.com/jupyter/dockerspawner.git && \
    pip install git+git://github.com/jupyter/oauthenticator.git

RUN mkdir /srv/jupyterhub_config
WORKDIR /srv/jupyterhub_config

ADD remote_user_auth.py /srv/jupyterhub_config/remote_user_auth.py
ADD swarmspawner.py /srv/jupyterhub_config/swarmspawner.py
ADD jupyterhub_config.py /srv/jupyterhub_config/jupyterhub_config.py

RUN mkdir /srv/jupyterhub_users

EXPOSE 8080
EXPOSE 8001

# environment variable for swarm
ENV DOCKER_HOST https://swarm:2375
ENV TZ America/Chicago

ENTRYPOINT ["jupyterhub", "-f", "/srv/jupyterhub_config/jupyterhub_config.py", "&>", "/srv/jupyterhub/jupyterhub.log"]

