FROM jupyter/jupyterhub:latest

MAINTAINER Edward J Kim <edward.junhyung.kim@gmail.com>

RUN apt-get update && \
    pip3 install --upgrade pip && \
    pip3 install docker-py && \
    pip3 install git+git://github.com/jupyter/dockerspawner.git && \
    pip3 install git+git://github.com/jupyter/oauthenticator.git

RUN mkdir /srv/jupyterhub_config
WORKDIR /srv/jupyterhub_config

ADD remote_user_auth.py /srv/jupyterhub_config/remote_user_auth.py
ADD swarmspawner.py /srv/jupyterhub_config/swarmspawner.py
ADD jupyterhub_config.py /srv/jupyterhub_config/jupyterhub_config.py

RUN mkdir /srv/jupyterhub_users

EXPOSE 8080
EXPOSE 8001

# environment variable for swarm
ENV DOCKER_HOST https://swarm:2375

# disable "Stop My Server" button since it doesn't work with Apache
RUN sed -i '/Stop My Server/s/<a id="stop".*<\/a>/<a id="stop"><\/a>/' /usr/local/share/jupyter/hub/templates/home.html
# disable "Logout" button since we can't log out of a Shibboleth session from Jupyterhub
RUN sed -i '/Logout/s/<a id="logout".*<\/a>/<a id="logout"><\/a>/' /usr/local/share/jupyter/hub/templates/page.html

ENTRYPOINT ["jupyterhub", "-f", "/srv/jupyterhub_config/jupyterhub_config.py"]

