#!/bin/bash

ROOT=$(dirname $0)/..

if [ ! -e ${ROOT}//inventory ]; then
  echo "Please create an inventory file with your hosts."
  echo " cp inventory.example inventory"
  exit 1
fi

exec ansible-playbook ${ROOT}/pull_data.yml -i ${ROOT}/inventory --ask-pass --ask-vault-pass -c paramiko $@
