consul:
  build: /srv/consul
  hostname: "{{ inventory_hostname }}"
  restart: always
  net: host
  volumes:
    - /root/.docker:/root/.docker
    - /srv/consul:/consul/data
    - /root/consul/config:/consul/config
  command: >
    agent
    -server
    -bootstrap
    "-advertise={{ private_ip }}"
    "-retry-join={{ private_ip }}"
    -disable-host-node-id=true
