---
- name: install vim for ops sanity
  apt: name=vim update_cache=yes state=latest

- name: install python
  apt: name=python update_cache=yes state=latest

- name: install pip
  apt: name=python-pip update_cache=yes state=latest
