---
- name: install vim for ops sanity
  apt: name=vim update_cache=yes state=latest

- name: install python
  apt: name=python state=latest

- name: install pip
  apt: name=python-pip state=latest

- name: upgrade pip
  apt: name=pip state=latest

- name: upgrade all packages
  apt: name=* state=latest
