---
- name: install nfs pakcages
  apt: name=nfs-common update_cache=yes state=latest

- name: unmount home
  shell: umount /home || true

- name: mount home
  mount: name=/home src={{ hostvars['nfs_server']['private_ip'] }}:/home fstype=nfs opts={{ nfsoptions }} state=mounted
